import Head from "next/head";
import Logo from "../components/index/LeftComponent/Logo";
import Menu from "../components/index/LeftComponent/Menu";
import Library from "../components/index/LeftComponent/Library";
import Customize from "../components/index/LeftComponent/Customize";
import Logout from "../components/index/LeftComponent/Logout";
import TrendingMusic from "../components/index/MiddleComponent/TrendingMusic";
import RecentlyPlayed from "../components/index/MiddleComponent/RecentlyPlayed";
import FavoriteHome from "../components/index/MiddleComponent/FavoriteHome";
import Account from "../components/index/RightComponent/Account";
import SearchBar from "../components/index/MiddleComponent/SearchBar";
import SearchResult from "../components/index/MiddleComponent/SearchResult";
import AudioPlayer from "../components/index/RightComponent/AudioPlayer";
import { useState } from "react";
import Loading from "./loading";
import { auth } from "../lib/firebase";
import { useAuthState } from "react-firebase-hooks/auth";
import { useRouter } from "next/router";
import Song from "../components/index/MiddleComponent/song";
import Recents from "../components/index/MiddleComponent/Recents";
import Favorites from "../components/index/MiddleComponent/Favorites";
import Trendings from "../components/index/MiddleComponent/Trendings";
import Plan from "../components/index/RightComponent/Plan";
import AddPlaylist from "../components/index/MiddleComponent/AddPlaylist";
import Playlists from "../components/index/MiddleComponent/Playlists";
import AccountDetails from "../components/index/MiddleComponent/Account";

// Mobile components
import BottomMenu from "../mobileComponents/BottomMenu/BottomMenu";
import TopHeader from "../mobileComponents/TopHeader/TopHeader";
import LibraryMobile from "../mobileComponents/Library/Library";
import RecentlyPlayedMobile from "../mobileComponents/RecentlyPlayed/RecentlyPlayed";
import AudioPlayerMobile from "../mobileComponents/AudioPlayerMobile/AudioPlayerMobile";
import AudioPlayerMobileMini from "../mobileComponents/AudioPlayerMobile/AudioPlayerMobileMini";

export default function Home() {
  const router = useRouter();
  const [user, loading, error] = useAuthState(auth);
  if (user) {
    return <HomeComponent />;
  } else if (loading) {
    return <Loading />;
  } else {
    router.push("/authenticate");
  }
}

function HomeComponent() {
  const [active, setActive] = useState(1);
  const [search, setSearch] = useState("");
  const [songId, setSongId] = useState(null);
  const [queue, setQueue] = useState([]);
  const [index, setIndex] = useState(null);
  const [currentSongId, setCurrentSongId] = useState(null);
  const [isPlaying, setIsPlaying] = useState<boolean>(false);
  const [maxAudioPlayer, setMaxAudioPlayer] = useState<boolean>(false);
  return (
    <>
      <Head>
        <title>Musicify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Vector-logo.png" />
      </Head>
      <main className="max-lg:hidden w-screen h-screen bg-gray-900 flex flex-row overflow-hidden">
        {/* Left Section of the page */}
        <div className="h-full lg:w-[250px] lg:visible collapse bg-[#1d242c] flex flex-col">
          <Logo active={active} setActive={setActive} />
          <div className="overflow-scroll">
            <Menu active={active} setActive={setActive} />
            <Library active={active} setActive={setActive} />
            <Customize active={active} setActive={setActive} />
          </div>
          <Logout />
        </div>

        {/* Middle Section of the page */}
        <div className="h-full flex-1">
          {!songId ? (
            {
              1: (
                <div className="flex flex-col h-screen overflow-scroll">
                  <div className="h-screen mx-8">
                    <TrendingMusic
                      setSongId={setSongId}
                      songId={songId}
                      setQueue={setQueue}
                      setIndex={setIndex}
                      currentSongId={currentSongId}
                      setCurrentSongId={setCurrentSongId}
                      isPlaying={isPlaying}
                      setIsPlaying={setIsPlaying}
                    />
                    <div className="flex flex-col mt-[250px]">
                      <div className="h-[290px]">
                        <RecentlyPlayed setSongId={setSongId} />
                      </div>
                      <div className="h-[290px]">
                        <FavoriteHome setSongId={setSongId} />
                      </div>
                    </div>
                  </div>
                </div>
              ),
              2: (
                <div className="flex flex-col h-screen">
                  <Trendings setSongId={setSongId} />
                </div>
              ),
              4: (
                <div className="flex flex-col h-screen">
                  <SearchBar search={search} setSearch={setSearch} />
                  <SearchResult search={search} setSongId={setSongId} />
                </div>
              ),
              5: (
                <div className="flex flex-col h-screen">
                  <Recents setSongId={setSongId} />
                </div>
              ),
              6: (
                <div className="flex flex-col h-screen">
                  <Playlists setSongId={setSongId} setActive={setActive} />
                </div>
              ),
              7: (
                <div className="flex flex-col h-screen">
                  <Favorites setSongId={setSongId} />
                </div>
              ),
              8: (
                <div className="flex flex-col h-screen">
                  <AddPlaylist />
                </div>
              ),
              9: (
                <div className="flex flex-col h-screen">
                  <AccountDetails />
                </div>
              ),
            }[active]
          ) : (
            <div className="">
              <Song
                setSongId={setSongId}
                songId={songId}
                setQueue={setQueue}
                setIndex={setIndex}
                currentSongId={currentSongId}
                setCurrentSongId={setCurrentSongId}
                isPlaying={isPlaying}
                setIsPlaying={setIsPlaying}
              />
            </div>
          )}
        </div>

        {/* Right Section of the page */}
        <div className="h-full w-[350px] bg-[#1d242c] flex flex-col">
          <Account setActive={setActive} />
          <Plan />
          <AudioPlayer
            isPlaying={isPlaying}
            setIsPlaying={setIsPlaying}
            queue={queue}
            currentIndex={index}
            setCurrentIndex={setIndex}
            currentSongId={currentSongId}
            setCurrentSongId={setCurrentSongId}
          />
        </div>
      </main>
      <main className="max-lg:visible lg:hidden w-screen h-screen bg-[#1c1c1c]">
        <div className="w-screen h-screen flex justify-center items-center text-white">
          Mobile Device Not Compatible
        </div>
        {/*<div className="w-screen h-screen flex flex-col">
          <div className="flex-1">
            {!songId ? (
              {
                1: (
                  <div className="flex flex-col h-screen overflow-scroll">
                    <div className=" h-[100px]">
                      <TopHeader setActive={setActive} active={active} />
                    </div>
                    <div className="px-4">
                      <RecentlyPlayedMobile setSongId={setSongId} />
                    </div>
                  </div>
                ),
                4: (
                  <div className="flex flex-col h-screen overflow-scroll">
                    <SearchBar search={search} setSearch={setSearch} />
                    <SearchResult search={search} setSongId={setSongId} />
                  </div>
                ),
                5: (
                  <div className="flex flex-col h-screen">
                    <Recents setSongId={setSongId} />
                  </div>
                ),
                6: (
                  <div className="flex flex-col h-screen">
                    <LibraryMobile
                      setSongId={setSongId}
                      active={active}
                      setActive={setActive}
                    />
                  </div>
                ),
                7: (
                  <div className="flex flex-col h-screen">
                    <LibraryMobile
                      setSongId={setSongId}
                      active={active}
                      setActive={setActive}
                    />
                  </div>
                ),
                8: (
                  <div className="flex flex-col h-screen">
                    <AddPlaylist />
                  </div>
                ),
                9: (
                  <div className="flex flex-col h-screen">
                    <AccountDetails setActive={setActive} />
                  </div>
                ),
              }[active]
            ) : (
              <div className="">
                <Song
                  setSongId={setSongId}
                  songId={songId}
                  setQueue={setQueue}
                  setIndex={setIndex}
                  currentSongId={currentSongId}
                  setCurrentSongId={setCurrentSongId}
                  isPlaying={isPlaying}
                  setIsPlaying={setIsPlaying}
                />
              </div>
            )}
          </div>

          <AudioPlayerMobile
            isPlaying={isPlaying}
            setIsPlaying={setIsPlaying}
            queue={queue}
            currentIndex={index}
            setCurrentIndex={setIndex}
            currentSongId={currentSongId}
            setCurrentSongId={setCurrentSongId}
            setMaxAudioPlayer={setMaxAudioPlayer}
            maxAudioPlayer={maxAudioPlayer}
          />


          <div className="fixed w-full bottom-0 bg-[#222222] h-[80px]">
            <BottomMenu active={active} setActive={setActive} />
          </div>
        </div>*/}
      </main>
    </>
  );
}
